// Card soldiers: one body, four suits. Same pixels, different pip + trim,
// so the whole squad costs one sprite's worth of authoring.
import { writeFileSync } from 'node:fs';
import { Grid } from './grid.mjs';

const PIPS = {
  hearts: [
    '.XX.XX.',
    'XXXXXXX',
    'XXXXXXX',
    'XXXXXXX',
    '.XXXXX.',
    '..XXX..',
    '...X...',
  ],
  spades: [
    '...X...',
    '..XXX..',
    '.XXXXX.',
    'XXXXXXX',
    'XXXXXXX',
    '..X.X..',
    '..XXX..',
  ],
  clubs: [
    '..XXX..',
    '..XXX..',
    'XX.X.XX',
    'XXXXXXX',
    'XX.X.XX',
    '...X...',
    '..XXX..',
  ],
  diamonds: [
    '...X...',
    '..XXX..',
    '.XXXXX.',
    'XXXXXXX',
    '.XXXXX.',
    '..XXX..',
    '...X...',
  ],
};

// Suit ink + the helmet/trim colour that goes with it.
const SUITS = {
  hearts:   { ink: 'r', lit: 'R', trim: 'r', label: 'Hearts' },
  spades:   { ink: '1', lit: '2', trim: '2', label: 'Spades' },
  clubs:    { ink: '2', lit: '3', trim: '3', label: 'Clubs' },
  diamonds: { ink: 'r', lit: 'R', trim: 'y', label: 'Diamonds' },
};

function guard(suit, step) {
  const { ink, lit, trim } = SUITS[suit];
  const g = new Grid(16, 16, '.');

  // spear, planted on the right
  g.vline(14, 0, 14, '2');
  g.set(14, 0, '5'); g.set(14, 1, '5'); g.set(13, 1, '0'); g.set(15, 1, '0');

  // head above the card
  g.blit(['0000', `0${trim}${trim}0`, '0ss0', 's00s', '0ss0'].map(r => r), 5, 0, ' ');

  // card body
  g.frame(1, 5, 13, 9, '0');
  g.rect(2, 6, 11, 7, '6');
  // corner pips
  g.set(3, 7, ink); g.set(11, 11, ink);
  g.set(3, 8, lit); g.set(11, 10, lit);
  // centre pip
  PIPS[suit].forEach((row, j) => [...row].forEach((ch, i) => {
    if (ch === 'X') g.set(4 + i, 6 + j, j < 2 ? lit : ink);
  }));
  // card shading
  g.vline(12, 6, 7, '5'); g.hline(2, 12, 11, '5');

  // legs
  const off = step ? 1 : 0;
  g.rect(4 - off, 14, 3, 2, '2'); g.frame(4 - off, 14, 3, 2, '0');
  g.rect(9 + off, 14, 3, 2, '2'); g.frame(9 + off, 14, 3, 2, '0');
  return g;
}

const CARDS = {};
for (const [suit, meta] of Object.entries(SUITS)) {
  CARDS[`guard_${suit}`] = {
    label: `Card Soldier - ${meta.label}`,
    blurb: `A token with a spear. ${meta.label} squad guards the ${suit === 'hearts' ? 'Queen' : 'gates'}.`,
    w: 16, h: 16,
    anim: { down: [0, 1] },
    frames: [guard(suit, 0), guard(suit, 1)],
  };
}

const fmt = (rows) => rows.map(r => `        '${r}',`).join('\n');
const out = `// Alice in AI Land - card soldiers (16x16).
// GENERATED by tools/gen-cards.mjs - edit the generator, not this file.

export const CARDS = {
${Object.entries(CARDS).map(([id, c]) => `  ${id}: {
    label: ${JSON.stringify(c.label)},
    blurb: ${JSON.stringify(c.blurb)},
    w: 16, h: 16,
    anim: ${JSON.stringify(c.anim)},
    frames: [
${c.frames.map(f => `      [\n${fmt(f.rows())}\n      ],`).join('\n')}
    ],
  },`).join('\n')}
};
`;
writeFileSync(new URL('../assets/sprites.cards.js', import.meta.url), out);
console.log(`cards: ${Object.keys(CARDS).length}`);
