// Bosses are drawn as a 16-wide LEFT HALF and mirrored to 32 wide.
// Halving the work also guarantees the silhouette is perfectly symmetric.
import { writeFileSync } from 'node:fs';

const mirror = (half) => half.map(r => r + [...r].reverse().join(''));

const JABBERWOCK_A = [
  '................',
  '.....00.........',
  '....0mm0........',
  '....0mm0........',
  '.....0mm0.......',
  '......0mmm0.....',
  '.....00mmmm0....',
  '...000mmmmmm000.',
  '..01mmmmmmmmmmm0',
  '.01mmmmmmmmmmmmm',
  '01mmmmmmmmmmmmmm',
  '0mmm000000mmmmmm',
  '0mm0gg0g0mmmmmmm',
  '0mmm000000mmmmmm',
  '.01mmmmmmmmmmmmm',
  '..01mmmmmmmmmmmm',
  '...0mmmmm0666666',
  '....0mmm06066066',
  '.....0mm00666666',
  '......0mmm000000',
  '.......0mmmmmmmm',
  '.......0mmmmmmmm',
  '.......0mm444444',
  '.......0m4444444',
  '.......0mg44444g',
  '.......0mm444444',
  '.......0mmmmmmmm',
  '........0mmmmmmm',
  '........0mmmmmmm',
  '.........0mmmmmm',
  '..........000000',
  '................',
];

// Same pose, jaws open + wings beating: swap a few rows.
const JABBERWOCK_B = JABBERWOCK_A.slice();
// jaws open, wings beating, fire in the throat
JABBERWOCK_B[6]  = '....00mmmmm0....';
JABBERWOCK_B[7]  = '.0000mmmmmmm0000';
JABBERWOCK_B[8]  = '01mmmmmmmmmmmmm0';
JABBERWOCK_B[16] = '...0mmmmm0666666';
JABBERWOCK_B[17] = '....0mmm00666066';
JABBERWOCK_B[18] = '.....0mm0oooooo6';
JABBERWOCK_B[19] = '......0mm0oooooo';
JABBERWOCK_B[20] = '.......0mmm0oooo';

const QUEEN_TITAN_A = [
  '................',
  '......y.y.y.y.y.',
  '......yyyyyyyyyy',
  '......0yyyyyyyyy',
  '.....01111111111',
  '.....01sssssssss',
  '.....01s0ssssss0',
  '.....01ssssssrrr',
  '.....011ssssssss',
  '......0116666666',
  '....002rrrrr66rr',
  '...02rrrrrrr6rrr',
  '..02rrrrrrrrrrrr',
  '..0rrr666rrrrrrr',
  '..0rr66666rrrrrr',
  '..0rr66r66rrrrrr',
  '..0rrr666rrrrrrr',
  '..0rrrr6rrrrrrrr',
  '..0rrrrrrrrrrrrr',
  '..0rrrrrrrrrrrrr',
  '.02rrrrrrrrrrrrr',
  '.02rrrrrrrrrrrrr',
  '.02rrrrrrrrrrrrr',
  '.02rrrrrrrrrrrrr',
  '02rrrrrrrrrrrrrr',
  '02rrrrrrrrrrrrrr',
  '02rrrrrrrrrrrrrr',
  '0rrrrrrrrrrrrrrr',
  '0rrrrrrrrrrrrrrr',
  '0rrrrrrrrrrrrrrr',
  '0000000000000000',
  '................',
];

const QUEEN_TITAN_B = QUEEN_TITAN_A.slice();
QUEEN_TITAN_B[13] = '..0rrrrrrrrrrrrr';
QUEEN_TITAN_B[14] = '..0rr666rrrrrrrr';
QUEEN_TITAN_B[15] = '..0r66666rrrrrrr';
QUEEN_TITAN_B[16] = '..0r66r66rrrrrrr';
QUEEN_TITAN_B[17] = '..0rr666rrrrrrrr';
QUEEN_TITAN_B[18] = '..0rrr6rrrrrrrrr';

const BOSSES = {
  jabberwock: {
    label: 'The Jabberwock',
    blurb: 'A model that grew past its spec. Beware the jaws that bite.',
    w: 32, h: 32,
    anim: { idle: [0, 1] },
    frames: [mirror(JABBERWOCK_A), mirror(JABBERWOCK_B)],
  },
  queen_titan: {
    label: 'The Queen Ascendant',
    blurb: 'Final stage. She fills the room and the room is the board.',
    w: 32, h: 32,
    anim: { idle: [0, 1] },
    frames: [mirror(QUEEN_TITAN_A), mirror(QUEEN_TITAN_B)],
  },
};

const fmt = (rows) => rows.map(r => `        '${r}',`).join('\n');
const out = `// Alice in AI Land - boss sprites (32x32).
// GENERATED by tools/gen-bosses.mjs - edit the generator, not this file.

export const BOSSES = {
${Object.entries(BOSSES).map(([id, b]) => `  ${id}: {
    label: ${JSON.stringify(b.label)},
    blurb: ${JSON.stringify(b.blurb)},
    w: ${b.w}, h: ${b.h},
    anim: ${JSON.stringify(b.anim)},
    frames: [
${b.frames.map(f => `      [\n${fmt(f)}\n      ],`).join('\n')}
    ],
  },`).join('\n')}
};
`;
writeFileSync(new URL('../legacy/assets/sprites.bosses.js', import.meta.url), out);
console.log(`bosses: ${Object.keys(BOSSES).length}`);
